runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
handlers:
- url: /browser-extension.zip
  static_files: browser-extension.zip
  upload: browser-extension.zip
  secure: always
  
- url: /top-edit
  script: topedit.app
  secure: always
  
- url: /top-edits-list-1-page
  script: topeditslist1page.app
  secure: always
  
- url: /create-my-edit
  script: createmyedit.app
  secure: always
  
- url: /delete-my-edit
  script: deletemyedit.app
  secure: always

- url: /
  static_files: landing.html
  upload: landing.html
  secure: always
  
- url: /
  static_dir: static
  secure: always
